/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalassessment;

import java.util.Date;

/**
 *
 * @author rishidhir
 */
public class AddClub extends javax.swing.JFrame {
    private HomePage first; 
    /**
     * Creates new form add
     */
    public AddClub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClubPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        president = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        executive = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputPresident = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputPhone = new javax.swing.JTextField();
        inputExecutive = new javax.swing.JTextField();
        inputMoney = new javax.swing.JTextField();
        returnBtn = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        addClubText = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addClubPanel1 = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        president1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        executive1 = new javax.swing.JLabel();
        money1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        inputName1 = new javax.swing.JTextField();
        inputPresident1 = new javax.swing.JTextField();
        inputEmail1 = new javax.swing.JTextField();
        inputPhone1 = new javax.swing.JTextField();
        inputExecutive1 = new javax.swing.JTextField();
        inputMoney1 = new javax.swing.JTextField();
        returnBtn1 = new javax.swing.JButton();
        dateChooser1 = new com.toedter.calendar.JDateChooser();
        addClubText1 = new javax.swing.JLabel();
        saveBtn1 = new javax.swing.JButton();

        addClubPanel.setBackground(new java.awt.Color(36, 47, 65));

        name.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Club Name");

        president.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        president.setForeground(new java.awt.Color(255, 255, 255));
        president.setText("Club President");

        email.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Club Email");

        phone.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Club Phone Number");

        executive.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        executive.setForeground(new java.awt.Color(255, 255, 255));
        executive.setText("Number of Executives");

        money.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        money.setForeground(new java.awt.Color(255, 255, 255));
        money.setText("Money Given");

        date.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date ");

        inputName.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        inputPresident.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputEmail.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputPhone.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputExecutive.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputMoney.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        returnBtn.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        addClubText.setFont(new java.awt.Font("PT Sans", 1, 48)); // NOI18N
        addClubText.setForeground(new java.awt.Color(255, 255, 255));
        addClubText.setText("Add Club");

        saveBtn.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addClubPanelLayout = new javax.swing.GroupLayout(addClubPanel);
        addClubPanel.setLayout(addClubPanelLayout);
        addClubPanelLayout.setHorizontalGroup(
            addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(president)
                    .addComponent(email)
                    .addComponent(phone)
                    .addComponent(executive)
                    .addComponent(money)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputMoney)
                    .addComponent(inputExecutive)
                    .addComponent(inputPhone)
                    .addComponent(inputEmail)
                    .addComponent(inputPresident)
                    .addComponent(inputName)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanelLayout.createSequentialGroup()
                        .addComponent(addClubText)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanelLayout.createSequentialGroup()
                        .addComponent(returnBtn)
                        .addGap(43, 43, 43)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        addClubPanelLayout.setVerticalGroup(
            addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addClubText)
                .addGap(35, 35, 35)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(president)
                    .addComponent(inputPresident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executive)
                    .addComponent(inputExecutive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(money))
                .addGap(29, 29, 29)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(addClubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBtn)
                    .addComponent(saveBtn))
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_rsz_icon_process-improvement_600_600colo-255-255-255-0_1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_11photo.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        addClubPanel1.setBackground(new java.awt.Color(36, 47, 65));

        name1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("Club Name");

        president1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        president1.setForeground(new java.awt.Color(255, 255, 255));
        president1.setText("Club President");

        email1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setText("Club Email");

        phone1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        phone1.setForeground(new java.awt.Color(255, 255, 255));
        phone1.setText("Club Phone Number");

        executive1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        executive1.setForeground(new java.awt.Color(255, 255, 255));
        executive1.setText("Number of Executives");

        money1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        money1.setForeground(new java.awt.Color(255, 255, 255));
        money1.setText("Money Given");

        date1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("Date ");

        inputName1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        inputName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputName1ActionPerformed(evt);
            }
        });

        inputPresident1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputEmail1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputPhone1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputExecutive1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        inputMoney1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        returnBtn1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        returnBtn1.setText("Return");
        returnBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtn1ActionPerformed(evt);
            }
        });

        addClubText1.setFont(new java.awt.Font("PT Sans", 1, 48)); // NOI18N
        addClubText1.setForeground(new java.awt.Color(255, 255, 255));
        addClubText1.setText("Add Club");

        saveBtn1.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        saveBtn1.setText("Save");
        saveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addClubPanel1Layout = new javax.swing.GroupLayout(addClubPanel1);
        addClubPanel1.setLayout(addClubPanel1Layout);
        addClubPanel1Layout.setHorizontalGroup(
            addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name1)
                    .addComponent(president1)
                    .addComponent(email1)
                    .addComponent(phone1)
                    .addComponent(executive1)
                    .addComponent(money1)
                    .addComponent(date1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputMoney1)
                    .addComponent(inputExecutive1)
                    .addComponent(inputPhone1)
                    .addComponent(inputEmail1)
                    .addComponent(inputPresident1)
                    .addComponent(inputName1)
                    .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanel1Layout.createSequentialGroup()
                        .addComponent(addClubText1)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanel1Layout.createSequentialGroup()
                        .addComponent(returnBtn1)
                        .addGap(43, 43, 43)
                        .addComponent(saveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        addClubPanel1Layout.setVerticalGroup(
            addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClubPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addClubText1)
                .addGap(35, 35, 35)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(inputName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(president1)
                    .addComponent(inputPresident1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1)
                    .addComponent(inputEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1)
                    .addComponent(inputPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executive1)
                    .addComponent(inputExecutive1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMoney1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(money1))
                .addGap(29, 29, 29)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(addClubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBtn1)
                    .addComponent(saveBtn1))
                .addGap(35, 35, 35))
        );

        getContentPane().add(addClubPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 640, 650));

        setSize(new java.awt.Dimension(899, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void addClub (HomePage h) {
        first = h;
        inputName1.setText(" ");
        inputPresident1.setText(" ");
        inputEmail1.setText(" ");
        inputPhone1.setText(" ");
        inputExecutive1.setText(" ");
        inputMoney1.setText(" ");         
    }
    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO AddClub your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO AddClub your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

    }//GEN-LAST:event_saveBtnActionPerformed

    private void inputName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputName1ActionPerformed
        // TODO AddClub your handling code here:
    }//GEN-LAST:event_inputName1ActionPerformed

    private void returnBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtn1ActionPerformed
        // TODO AddClub your handling code here:
        this.setVisible(false);
        first.setVisible(true);
    }//GEN-LAST:event_returnBtn1ActionPerformed

    private void saveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn1ActionPerformed
        // TODO AddClub your handling code here:
        String name = inputName1.getText();
        String president = inputPresident1.getText();
        String email = inputEmail1.getText();
        String phone = inputPhone1.getText();
        String executive = inputExecutive1.getText();
        Date date = dateChooser1.getDate();
        String money = inputMoney1.getText();

        Club h = new Club(name,president,email,phone,executive,date,money);
        first.addClub(h);
        dateChooser1.setDate(null);
        this.setVisible(false);
        first.setVisible(true);
    }//GEN-LAST:event_saveBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addClubPanel;
    private javax.swing.JPanel addClubPanel1;
    private javax.swing.JLabel addClubText;
    private javax.swing.JLabel addClubText1;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateChooser1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel executive;
    private javax.swing.JLabel executive1;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputEmail1;
    private javax.swing.JTextField inputExecutive;
    private javax.swing.JTextField inputExecutive1;
    private javax.swing.JTextField inputMoney;
    private javax.swing.JTextField inputMoney1;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputName1;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JTextField inputPhone1;
    private javax.swing.JTextField inputPresident;
    private javax.swing.JTextField inputPresident1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel money;
    private javax.swing.JLabel money1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel president;
    private javax.swing.JLabel president1;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton returnBtn1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton saveBtn1;
    // End of variables declaration//GEN-END:variables
}
