/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalassessment;

import javax.swing.JOptionPane;

/**
 *
 * @author rishidhir
 */
public class DeleteClub extends javax.swing.JFrame {
    private HomePage first; 
    private SAC account; 
    /**
     * Creates new form DeleteClub
     */
    public DeleteClub() {
        initComponents();
    }
    
    public void deleteClubList(SAC a, HomePage p) {
        account = a;
        first = p;
        int count = account.getCount();
        String n;
        account.sortClub();
        Club [] listClub = account.getClub();
        if (count == 0) {
            n = "No Clubs to Delete";
        }
        else {
         n = "";
        for (int i=0; i < count; i++) {
             String temp2 = Integer.toString(i+1);
             n = n+temp2+". "+listClub[i].getName()+" \n";
            }
        } 
        deleteClubTxt.setText(n);
        deleteClubTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchClub = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deleteClubTxt = new javax.swing.JTextArea();
        deleteClubLabel = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        clubNumberLabel = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        searchNumberTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSearchClub.setBackground(new java.awt.Color(36, 47, 65));

        deleteClubTxt.setColumns(20);
        deleteClubTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        deleteClubTxt.setRows(5);
        deleteClubTxt.setBorder(null);
        jScrollPane2.setViewportView(deleteClubTxt);

        deleteClubLabel.setFont(new java.awt.Font("PT Sans", 1, 48)); // NOI18N
        deleteClubLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteClubLabel.setText("Delete Club");

        deleteBtn.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        deleteBtn.setMnemonic('E');
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clubNumberLabel.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        clubNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        clubNumberLabel.setText("Enter Club Number to Delete");

        returnBtn.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        searchNumberTxt.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        searchNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNumberTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchClubLayout = new javax.swing.GroupLayout(panelSearchClub);
        panelSearchClub.setLayout(panelSearchClubLayout);
        panelSearchClubLayout.setHorizontalGroup(
            panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchClubLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(clubNumberLabel)
                .addGap(50, 50, 50)
                .addComponent(searchNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(deleteBtn)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                        .addComponent(deleteClubLabel)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                        .addComponent(returnBtn)
                        .addGap(261, 261, 261))))
        );
        panelSearchClubLayout.setVerticalGroup(
            panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(deleteClubLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubNumberLabel)
                    .addComponent(searchNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addGap(45, 45, 45)
                .addComponent(returnBtn)
                .addGap(33, 33, 33))
        );

        getContentPane().add(panelSearchClub, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 650, 640));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_rsz_icon_process-improvement_600_600colo-255-255-255-0_1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_11photo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        setSize(new java.awt.Dimension(910, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(null, "Do you want to Delete this club?", "Delete", JOptionPane.YES_NO_OPTION);
        if (delete==0) {
            String temp = searchNumberTxt.getText();
            int temp2 = Integer.parseInt(temp);
            account.deleteClub(temp2);   
            String sort; 
            int count = account.getCount();
            Club [] listClub = account.getClub();
            if (count ==0) {
                sort = "No clubs to Delete";
            }
            else {
                sort = "";
                for(int i = 0; i<count; i++) {
                    String temp5 = Integer.toString(i+1);
                    sort = sort+temp5+". "+ listClub[i].getName()+" \n";              
                }
            }
            deleteClubTxt.setText(sort);
            searchNumberTxt.setText("");
            deleteClubTxt.setEditable(false);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        first.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void searchNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNumberTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clubNumberLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deleteClubLabel;
    private javax.swing.JTextArea deleteClubTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelSearchClub;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTextField searchNumberTxt;
    // End of variables declaration//GEN-END:variables
}
