/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalassessment;
/**
 *
 * @author rishidhir
 */
public class EditClub extends javax.swing.JFrame {
    
    private HomePage first; 
    private SAC account; 
    private ExtensionEditClub extension = new ExtensionEditClub(); 
    
    /**
     * Creates new form SearchClub
     */
    public EditClub() {
        initComponents();
    }
    
    public void clubList(SAC a, HomePage p){
        account = a;
        first = p;
        int count = account.getCount();
        String n;
        account.sortClub();
        Club [] listClub = account.getClub();
        if (count == 0) {
            n = "No Clubs to Edit";
        }
        else {
         n = "";
        for (int i=0; i < count; i++) {
             String temp2 = Integer.toString(i+1);
             n = n+temp2+". "+listClub[i].getName()+" \n";
        }
        }
        clubListTxt.setText(n);     
        clubListTxt.setEditable(false);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelSearchClub = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clubListTxt = new javax.swing.JTextArea();
        searchClubLabel = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        clubNumberLabel = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        searchNumberTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_rsz_icon_process-improvement_600_600colo-255-255-255-0_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_11photo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSearchClub.setBackground(new java.awt.Color(36, 47, 65));

        clubListTxt.setColumns(20);
        clubListTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        clubListTxt.setRows(5);
        clubListTxt.setBorder(null);
        jScrollPane2.setViewportView(clubListTxt);

        searchClubLabel.setFont(new java.awt.Font("PT Sans", 1, 48)); // NOI18N
        searchClubLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchClubLabel.setText("Edit Club");

        editBtn.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        editBtn.setMnemonic('E');
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        clubNumberLabel.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        clubNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        clubNumberLabel.setText("Enter Club Number to Edit");

        returnBtn.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        searchNumberTxt.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelSearchClubLayout = new javax.swing.GroupLayout(panelSearchClub);
        panelSearchClub.setLayout(panelSearchClubLayout);
        panelSearchClubLayout.setHorizontalGroup(
            panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchClubLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(clubNumberLabel)
                .addGap(50, 50, 50)
                .addComponent(searchNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(editBtn)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                        .addComponent(searchClubLabel)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                        .addComponent(returnBtn)
                        .addGap(262, 262, 262))))
        );
        panelSearchClubLayout.setVerticalGroup(
            panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchClubLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(searchClubLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelSearchClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clubNumberLabel)
                    .addComponent(searchNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn))
                .addGap(56, 56, 56)
                .addComponent(returnBtn)
                .addGap(22, 22, 22))
        );

        getContentPane().add(panelSearchClub, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 650, 640));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_rsz_icon_process-improvement_600_600colo-255-255-255-0_1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalassessment/rsz_11photo.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        setSize(new java.awt.Dimension(910, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        first.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String temp = searchNumberTxt.getText();
        int temp2 = Integer.parseInt(temp);
        Club [] clubs = account.getClub();
        Club c = clubs[temp2-1];
        extension.display(first, this, c, account, temp2-1);
        searchNumberTxt.setText("");
        this.setVisible(false);  
        extension.setVisible(true);  
    }//GEN-LAST:event_editBtnActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea clubListTxt;
    private javax.swing.JLabel clubNumberLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelSearchClub;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel searchClubLabel;
    private javax.swing.JTextField searchNumberTxt;
    // End of variables declaration//GEN-END:variables
}
